const globalstyles = {
    scoreStatsContainer: {
      flex: 1,
      padding: "1vw",
      // padding: "15px",
      borderLeft: "0.1vw solid #ddd",
      // borderLeft: "1px solid #ddd",
      backgroundColor: "#f8f9fa",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      // height: "100%",
    },
    scoreStats: {
      backgroundColor: "#ffffff",
      padding: "1vw 1.2vw",
      // padding: "15px 20px",
      border: "0.1vw solid #ddd",
      // border: "1px solid #ddd",
      borderRadius: "0.5vw",
      // // borderRadius: "8px",
      boxShadow: "0 0.1vw 0.2vw rgba(0,0,0,0.1)",
      // boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      textAlign: "center",
      // fontSize: "16px",
      width: "100%",
      maxWidth: "20vw",
      // maxWidth: "250px",
    },
    heading: {
      fontSize: "1.3vw",
      // fontSize: "18px",
      fontWeight: "bold",
      marginBottom: "0.5vw",
      // marginBottom: "10px",
      color: "#333",
    },
    statItem: {
      marginBottom: "0.5vw",
      // marginBottom: "10px",
      fontSize: "1.2vw",
      // fontSize: "16px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: "0.1vw solid #e0e0e0",
      // borderBottom: "1px solid #e0e0e0",
      paddingBottom: "0.2vw",
      // paddingBottom: "5px",
    },
    statLabel: {
      fontWeight: "500",
      color: "#555",
    },
    statValue: {
      fontWeight: "700",
      color: "#007BFF",
    },
  };
  
  export default globalstyles;
  